"""
QuantSignal India — Maximum Stock Universe
~500 liquid NSE stocks across all sectors for maximum profit opportunity.
Geopolitical themes: Defence, PSU Banks, Infra, Energy, IT, Pharma, EV, Chemicals, Telecom, FMCG, Metals, Realty
"""

# ── NIFTY 50 ─────────────────────────────────────────────────────────────────
_N50 = [
    "RELIANCE.NS","TCS.NS","HDFCBANK.NS","INFY.NS","ICICIBANK.NS",
    "HINDUNILVR.NS","SBIN.NS","BHARTIARTL.NS","KOTAKBANK.NS","LT.NS",
    "ITC.NS","AXISBANK.NS","BAJFINANCE.NS","ASIANPAINT.NS","MARUTI.NS",
    "HCLTECH.NS","SUNPHARMA.NS","TITAN.NS","ULTRACEMCO.NS","WIPRO.NS",
    "NESTLEIND.NS","BAJAJFINSV.NS","TATAMOTORS.NS","POWERGRID.NS","NTPC.NS",
    "ONGC.NS","JSWSTEEL.NS","M&M.NS","TATASTEEL.NS","ADANIENT.NS",
    "ADANIPORTS.NS","COALINDIA.NS","GRASIM.NS","TECHM.NS","INDUSINDBK.NS",
    "HINDALCO.NS","DRREDDY.NS","DIVISLAB.NS","CIPLA.NS","BPCL.NS",
    "EICHERMOT.NS","BRITANNIA.NS","APOLLOHOSP.NS","TATACONSUM.NS","HEROMOTOCO.NS",
    "SBILIFE.NS","HDFCLIFE.NS","BAJAJ-AUTO.NS","UPL.NS","SHRIRAMFIN.NS",
]

# ── NIFTY NEXT 50 ─────────────────────────────────────────────────────────────
_NN50 = [
    "ADANIGREEN.NS","AMBUJACEM.NS","AUROPHARMA.NS","BANKBARODA.NS",
    "BERGEPAINT.NS","BOSCHLTD.NS","CANBK.NS","CHOLAFIN.NS","COLPAL.NS",
    "DABUR.NS","DLF.NS","GAIL.NS","GODREJCP.NS","HAVELLS.NS","ICICIPRULI.NS",
    "INDHOTEL.NS","INDUSTOWER.NS","IOC.NS","IRCTC.NS","JINDALSTEL.NS",
    "LICI.NS","LODHA.NS","LUPIN.NS","MARICO.NS","MCDOWELL-N.NS",
    "MUTHOOTFIN.NS","NAUKRI.NS","NHPC.NS","NMDC.NS","OBEROIRLTY.NS",
    "OFSS.NS","PAGEIND.NS","PIDILITIND.NS","PIIND.NS","PNB.NS",
    "RECLTD.NS","SAIL.NS","SIEMENS.NS","SRF.NS","TATAPOWER.NS",
    "TORNTPHARM.NS","TRENT.NS","UNIONBANK.NS","VBL.NS","VEDL.NS",
    "ZOMATO.NS","ZYDUSLIFE.NS","PFC.NS","BAJAJHLDNG.NS","GODREJPROP.NS",
]

# ── DEFENCE (India-US deal, +35% rally) ──────────────────────────────────────
_DEFENCE = [
    "HAL.NS","BEL.NS","BDL.NS","GRSE.NS","MAZDOCK.NS","MTAR.NS",
    "BEML.NS","COCHINSHIP.NS","ASTRA.NS","ZENTEC.NS","PARAS.NS","DPSL.NS",
    "SOLARA.NS","MIDHANI.NS","DATAPATTNS.NS","IDEAFORGE.NS",
]

# ── PSU BANKS (+31-68% YTD) ───────────────────────────────────────────────────
_PSU_BANKS = [
    "INDIANB.NS","BANKINDIA.NS","CENTRALBK.NS","UCOBANK.NS",
    "MAHABANK.NS","PSB.NS","JKBANK.NS","KARURVYSYA.NS","CSBBANK.NS",
    "DCBBANK.NS","FEDERALBNK.NS","SOUTHBANK.NS","LAKSHVILAS.NS",
]

# ── INFRA & RAILWAYS ──────────────────────────────────────────────────────────
_INFRA = [
    "RVNL.NS","IRFC.NS","IRCON.NS","KECL.NS","KALPATPOWR.NS",
    "NBCC.NS","NCC.NS","PNCINFRA.NS","HGINFRA.NS","CONCOR.NS",
    "APLAPOLLO.NS","JINDALSAW.NS","TIINDIA.NS","GPPL.NS","JSWINFRA.NS",
    "ADANIPORTS.NS","GMRINFRA.NS","IRB.NS","ASHOKA.NS","SADBHAV.NS",
    "KNRCON.NS","PSPPROJECT.NS","CAPACITE.NS","WELCORP.NS","RATNAMANI.NS",
]

# ── ENERGY & POWER ────────────────────────────────────────────────────────────
_ENERGY = [
    "TATAPOWER.NS","ADANIGREEN.NS","SJVN.NS","CESC.NS","TORNTPOWER.NS",
    "JSWENERGY.NS","SUZLON.NS","INOXWIND.NS","IOC.NS","OIL.NS",
    "MRPL.NS","PETRONET.NS","IGL.NS","MGL.NS","GUJGASLTD.NS",
    "ADANIGAS.NS","AEGASIND.NS","GUJRATGAS.NS","RPOWER.NS","JPPOWER.NS",
    "TRIL.NS","GREENPANEL.NS","ORIENTELEC.NS","KPIL.NS","THERMAX.NS",
]

# ── IT & TECH ─────────────────────────────────────────────────────────────────
_IT = [
    "LTIM.NS","MPHASIS.NS","PERSISTENT.NS","COFORGE.NS","KPITTECH.NS",
    "TATAELXSI.NS","ZENSARTECH.NS","MASTEK.NS","RATEGAIN.NS","NAUKRI.NS",
    "POLICYBZR.NS","PAYTM.NS","ZOMATO.NS","JIOFIN.NS","ANGELONE.NS",
    "HAPPSTMNDS.NS","SONATSOFTW.NS","TANLA.NS","ROUTE.NS","HFCL.NS",
    "STLTECH.NS","RAILTEL.NS","INTELLECT.NS","NEWGEN.NS","NUCLEUS.NS",
    "CYIENT.NS","BIRLASOFT.NS","HEXAWARE.NS","NIITLTD.NS","RATEGAIN.NS",
]

# ── PHARMA & HEALTHCARE ───────────────────────────────────────────────────────
_PHARMA = [
    "AUROPHARMA.NS","LUPIN.NS","TORNTPHARM.NS","ZYDUSLIFE.NS","ALKEM.NS",
    "IPCALAB.NS","GLENMARK.NS","NATCOPHARM.NS","LAURUSLABS.NS","GRANULES.NS",
    "FORTIS.NS","MAXHEALTH.NS","METROPOLIS.NS","THYROCARE.NS","SUVEN.NS",
    "AJANTPHARM.NS","JBCHEPHARM.NS","ERIS.NS","ABBOTINDIA.NS","PFIZER.NS",
    "SANOFI.NS","GLAXO.NS","BIOCON.NS","STRIDES.NS","SEQUENT.NS",
    "DIVI.NS","SOLARA.NS","LALPATHLAB.NS","KRSNAA.NS","VIJAYA.NS",
]

# ── METALS & MINING ───────────────────────────────────────────────────────────
_METALS = [
    "NATIONALUM.NS","HINDCOPPER.NS","MOIL.NS","WELCORP.NS","APLAPOLLO.NS",
    "JINDALSAW.NS","JSWINFRA.NS","TINPLATE.NS","KALYANKJIL.NS","MANAPPURAM.NS",
    "GOLDIAM.NS","RAJESHEXPO.NS","TITAN.NS","PCJEWELLER.NS","SENCO.NS",
    "EDELWEISS.NS","MSTCLTD.NS","NMDC.NS","COALINDIA.NS","VEDL.NS",
]

# ── AUTO & EV ─────────────────────────────────────────────────────────────────
_AUTO = [
    "ASHOKLEY.NS","TVSMOTOR.NS","BALKRISIND.NS","APOLLOTYRE.NS","MOTHERSON.NS",
    "BOSCHLTD.NS","BHARATFORG.NS","EXIDEIND.NS","AMARARAJA.NS","OLECTRA.NS",
    "CEATLTD.NS","MRF.NS","SUNDRMFAST.NS","SUPRAJIT.NS","ENDURANCE.NS",
    "CRAFTSMAN.NS","GABRIEL.NS","MINDA.NS","LUMAX.NS","SUBROS.NS",
    "SWARAJENG.NS","ESCORTS.NS","FORCEMOT.NS","MAHINDCIE.NS","TIINDIA.NS",
]

# ── FMCG & CONSUMER ───────────────────────────────────────────────────────────
_FMCG = [
    "EMAMILTD.NS","JYOTHYLAB.NS","RADICO.NS","MCDOWELL-N.NS","UNITDSPR.NS",
    "BIKAJI.NS","DEVYANI.NS","WESTLIFE.NS","JUBLFOOD.NS","SAPPHIRE.NS",
    "BARBEQUE.NS","SPECIALITY.NS","VSTIND.NS","GODFRYPHLP.NS","ITC.NS",
    "PATANJALI.NS","HATSUN.NS","HERITAGE.NS","PARAG.NS","DODLA.NS",
]

# ── FINANCIALS & NBFC ─────────────────────────────────────────────────────────
_FINANCE = [
    "MANAPPURAM.NS","LICHSGFIN.NS","PNBHOUSING.NS","CANFINHOME.NS",
    "CREDITACC.NS","UJJIVANSFB.NS","EQUITASBNK.NS","SBICARD.NS",
    "HDFCAMC.NS","NIPPONLIFE.NS","ICICIPRULI.NS","AAVAS.NS","HOMEFIRST.NS",
    "APTUS.NS","REPCO.NS","MAHINDRA.NS","SUNDARMFIN.NS","MMFS.NS",
    "IIFL.NS","MFSL.NS","ABSLAMC.NS","UTIAMC.NS","360ONE.NS",
    "NUVAMA.NS","MOTILALOFS.NS","ISEC.NS","GEOJITFSL.NS","SMCGLOBAL.NS",
]

# ── CHEMICALS ─────────────────────────────────────────────────────────────────
_CHEMICALS = [
    "ATUL.NS","DEEPAKNTR.NS","NAVINFLUOR.NS","FLUOROCHEM.NS","CLEAN.NS",
    "FINEORG.NS","TATACHEM.NS","GNFC.NS","COROMANDEL.NS","CHAMBLFERT.NS",
    "GSFC.NS","AARTI.NS","VINATI.NS","GALAXYSURF.NS","ROSSARI.NS",
    "ANUPAM.NS","SUDARSCHEM.NS","NOCIL.NS","NEOGEN.NS","PCBL.NS",
    "IGPL.NS","BASF.NS","AKZOINDIA.NS","KANSAINER.NS","BERGER.NS",
]

# ── REALTY & CEMENT ───────────────────────────────────────────────────────────
_REALTY = [
    "PRESTIGE.NS","BRIGADE.NS","SOBHA.NS","PHOENIXLTD.NS","MAHLIFE.NS",
    "KOLTEPATIL.NS","SUNTECK.NS","ARVSMART.NS","SHRIRAM.NS","NCLIND.NS",
    "SHREECEM.NS","JKCEMENT.NS","RAMCOCEM.NS","HEIDELBERG.NS","NUVOCO.NS",
    "DALMIA.NS","JKLAKSHMI.NS","BIRLACORPN.NS","PRISM.NS","ORIENT.NS",
]

# ── TELECOM & MEDIA ───────────────────────────────────────────────────────────
_TELECOM = [
    "IDEA.NS","TATACOMM.NS","RAILTEL.NS","ROUTE.NS","TANLA.NS",
    "ONMOBILE.NS","GTLINFRA.NS","INDIAMART.NS","JUSTDIAL.NS","INFOEDGE.NS",
    "ZOMATO.NS","SWIGGY.NS","NYKAA.NS","CARTRADE.NS","EASEMYTRIP.NS",
]

# ── SMALL/MID CAP HIGH VOLUME ─────────────────────────────────────────────────
_SMALLCAP = [
    "YESBANK.NS","IRFC.NS","RECLTD.NS","PFC.NS","ADANIPOWER.NS",
    "RVNL.NS","NBCC.NS","BHEL.NS","NATIONALUM.NS","HINDCOPPER.NS",
    "MOIL.NS","SUZLON.NS","INOXWIND.NS","OLECTRA.NS","UCOBANK.NS",
    "MAHABANK.NS","CENTRALBK.NS","PSB.NS","BANKINDIA.NS","JKBANK.NS",
    "RPOWER.NS","JPPOWER.NS","TRIL.NS","GMRINFRA.NS","IRB.NS",
    "ASHOKA.NS","KNRCON.NS","PSPPROJECT.NS","CAPACITE.NS","SADBHAV.NS",
    "IDEAFORGE.NS","DATAPATTNS.NS","MIDHANI.NS","PARAS.NS","DPSL.NS",
    "ZENTEC.NS","ASTRA.NS","COCHINSHIP.NS","GRSE.NS","MAZDOCK.NS",
    "MTAR.NS","BEML.NS","HAL.NS","BEL.NS","BDL.NS",
    "SJVN.NS","CESC.NS","TORNTPOWER.NS","JSWENERGY.NS","TATAPOWER.NS",
]

# ── MASTER UNIVERSE (deduplicated ~500 stocks) ────────────────────────────────
_all = (
    _N50 + _NN50 + _DEFENCE + _PSU_BANKS + _INFRA + _ENERGY +
    _IT + _PHARMA + _METALS + _AUTO + _FMCG + _FINANCE +
    _CHEMICALS + _REALTY + _TELECOM + _SMALLCAP
)
INTRADAY_STOCKS = list(dict.fromkeys(_all))

NIFTY_INDEX = "^NSEI"
INDIA_VIX = "^INDIAVIX"

# ── Parameters ────────────────────────────────────────────────────────────────
DEFAULT_CAPITAL = 5000
MAX_RISK_PER_TRADE = 0.02
INTRADAY_INTERVAL = "5m"
INTRADAY_PERIOD = "5d"
DAILY_PERIOD = "3mo"
MIN_CONFIDENCE = 0.55
MIN_VOLUME_RATIO = 1.2
MIN_RISK_REWARD = 1.5
RSI_PERIOD = 14
RSI_OVERSOLD = 35
RSI_OVERBOUGHT = 70
VWAP_ENABLED = True
EMA_SHORT = 9
EMA_LONG = 21
SUPERTREND_PERIOD = 10
SUPERTREND_MULTIPLIER = 3

# ── Sector groups for UI ──────────────────────────────────────────────────────
SECTOR_GROUPS = {
    "🛡️ Defence":      _DEFENCE,
    "🏦 PSU Banks":    _PSU_BANKS,
    "🏗️ Infra/Rail":   _INFRA,
    "⚡ Energy":        _ENERGY,
    "💻 IT/Tech":       _IT,
    "💊 Pharma":        _PHARMA,
    "⚙️ Metals":        _METALS,
    "🚗 Auto/EV":       _AUTO,
    "🛒 FMCG":          _FMCG,
    "💰 Finance":       _FINANCE,
    "🧪 Chemicals":     _CHEMICALS,
    "🏠 Realty/Cement": _REALTY,
    "📡 Telecom":       _TELECOM,
    "📈 Small/Mid Cap": _SMALLCAP,
}
